apiVersion: apps/v1
kind: Deployment
metadata:
  name: leave-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: leave-app
  template:
    metadata:
      labels:
        app: leave-app
    spec:
      containers:
      - name: leave-app-container
        image: 23mis0597/leave-app:v1
        ports:
        - containerPort: 8080
