package com.leaveapp;

public class LeaveApp {
    public static void main(String[] args) throws InterruptedException {
        System.out.println("Leave Management System is Running...");
        // This keeps the container alive so Kubernetes doesn't restart it
        while(true) {
            Thread.sleep(10000);
        }
    }
}
